[tool.poetry]
name = "orflaedi"
version = "0.1.0"
description = ""
authors = ["Jökull Sólberg Auðunsson <jokull@solberg.is>"]

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0.50.0"
jinja2 = "^2.11.1"
aiofiles = "^0.4.0"
sqlalchemy = "^1.3.13"
psycopg2 = "^2.8.4"
imgix = "^3.1.1"
python-dotenv = "^0.12.0"
uvicorn = "^0.11.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^19.10b0"
pylint = "^2.4.4"
scrapy = "^2.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
